apiVersion: v1
kind: Service
metadata:
  name: client-node-port
spec:
  type: NodePort
  ports:
  - port: 3050 # internal port for other pods to access (client server if needed) 
    targetPort: 3000 # any incoming traffic directed here(balanceed between pods)
    nodePort: 31515 # browser access to test out (gateway to proxy)
  selector:
    component: web